[[redirects]]
from = "/api/user/login"
to = https://fullstack-snei.onrender.com/api/user/login"

[[redirects]]
from = "/api/user/signin"
to = https://fullstack-snei.onrender.comapi/user/signin"

[[redirects]]
from = "/api/*"
to = https://fullstack-snei.onrender.com/api/:splat"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
