[[redirects]]
from = "/api/user/login"
to = "https://backnew-cbrd.onrender.com/api/user/login"

[[redirects]]
from = "/api/user/signin"
to = "https://backnew-cbrd.onrender.com/api/user/signin"

[[redirects]]
from = "/api/*"
to = "https://backnew-cbrd.onrender.com/api/:splat"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
